//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by USBDEMO.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDC_DEVICE_NUMBER               101
#define IDD_USBDEMO_DIALOG              102
#define IDS_DIALOGPAGE_DEVICE           102
#define IDC_OUTPUTSTR                   102
#define IDS_DIALOGPAGE_DESC             103
#define IDS_DIALOGPAGE_PIPES            104
#define IDS_DIALOGPAGE_DEVREQ           105
#define IDS_BUTTON_OPEN                 106
#define IDS_BUTTON_SCAN                 107
#define IDS_BUTTON_CLOSE                108
#define IDS_DEVICE_NUMBER               109
#define IDS_BUTTON_DEVICE_DESC          110
#define IDS_EDIT_CONFIG_DESC            111
#define IDS_BUTTON_CONFIG_DESC          112
#define IDS_EDIT_STRING_DESC            113
#define IDS_EDIT_STRING_DESC_LID        114
#define DS_BUTTON_STRING_DESC           115
#define IDS_EDIT_CONFIG_INDEX           116
#define IDS_BUTTON_DEVICE_QUALIFIER_DESC 117
#define IDS_BUTTON_STRING_DESC          118
#define IDS_EDIT_ANY_DESC_TYPE          119
#define IDS_EDIT_ANY_DESC_INDEX         120
#define IDS_EDIT_ANY_DESC_LENGTH        121
#define IDS_BUTTON_ANY_DESC             122
#define IDS_BUTTON_OUTPUT_WINDOW        123
#define IDS_BUTTON_CLEAR_OUTPUT_WINDOW  124
#define IDS_IDOK                        125
#define IDS_DIALOGPAGE_PLOT             126
#define IDS_DIALOGPAGE_AD               127
#define IDR_MAINFRAME                   128
#define IDD_DIALOGPAGE_DEVICE           132
#define IDD_DIALOGPAGE_DESC             133
#define IDD_DIALOGPAGE_DEVREQ           134
#define IDD_DIALOGPAGE_PIPES            135
#define IDD_OUTPUT_WINDOW               137
#define IDD_DIALOGPAGE_PLOT             138
#define IDD_DIALOGPAGE_AD               139
#define IDC_TAB_MAIN                    1000
#define IDC_BUTTON_GETCONINF            1001
#define IDC_BUTTON_GETPIPINF            1001
#define IDC_LIST_DEVICES                1002
#define IDC_BUTTON_PIPTOWIN             1002
#define IDC_BUTTON_PIPTOFILE            1003
#define IDC_EDIT_BREQUEST               1004
#define IDC_BUTTON_FILETOPIP            1004
#define IDC_EDIT_STRING_DESC            1005
#define IDC_COMBO_DIRECTION             1005
#define IDC_EDIT_STRING_DESC_LID        1006
#define IDC_COMBO_TYPE                  1006
#define IDC_BUTTON_DEVICE_QUALIFIER_DESC 1007
#define IDC_COMBO_RECIPIENT             1007
#define IDC_EDIT_WVALUE                 1008
#define IDC_EDIT_WINDEX                 1009
#define IDC_EDIT_BUFFER                 1010
#define IDC_EDIT_BUFFER_SIZE            1011
#define IDC_BUTTON_SCAN                 1012
#define IDC_BUTTON_OPEN                 1013
#define IDC_BUTTON_CLOSE                1014
#define IDC_BUTTON_DEVICE_DESC          1014
#define IDC_BUTTON_ANY_DESC             1015
#define IDC_BUTTON_ENDPOINT_DESC        1015
#define IDC_BUTTON_DEVICE_DESC2         1015
#define IDC_BUTTON_CONFIG_DESC          1016
#define IDC_BUTTON_STRING_DESC          1017
#define IDC_EDIT_CONFIG_DESC            1018
#define IDC_EDIT_ANY_DESC_TYPE          1019
#define IDC_EDIT_ANY_DESC_INDEX         1020
#define IDC_EDIT_ANY_DESC_LENGTH        1021
#define IDC_EDIT_OUTPUTWIN              1022
#define IDC_BUTTON_OUTPUT_WINDOW        1023
#define IDC_BUTTON_CLEAR_OUTPUT_WINDOW  1024
#define IDC_BUTTON1                     1027
#define IDC_IntfDesc                    1027
#define IDC_DA0                         1027
#define IDSTART                         1028
#define IDC_DA1                         1028
#define IDSTOP                          1029
#define IDC_DA2                         1029
#define IDC_STATIC_PLOT                 1030
#define IDC_DA3                         1030
#define IDC_DA4                         1031
#define IDC_DA5                         1032
#define IDC_DA6                         1033
#define IDC_DA7                         1034
#define IDC_BUTTON5                     1034
#define IDC_EDIT_DA0                    1035
#define IDC_RadioAD0                    1037
#define IDC_BTNAD                       1038
#define IDC_EDIT_DA4                    1039
#define IDC_EDIT_DA5                    1040
#define IDC_EDIT_DA6                    1041
#define IDC_EDIT_DA7                    1042
#define IDC_EDIT_DA1                    1043
#define IDC_EDIT_DA2                    1044
#define IDC_EDIT_DA3                    1045
#define IDC_EDIT_AD                     1046
#define IDC_EDIT_AD_CHANNEL             1047
#define IDC_RadioAD1                    1058
#define IDC_RadioAD2                    1059
#define IDC_RadioAD3                    1060
#define IDC_RadioAD4                    1061
#define IDC_RadioAD5                    1062
#define IDC_RadioAD6                    1063
#define IDC_RadioAD7                    1064

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
